apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Declare the namespace of longhorn
  - namespace-manifest.yaml
  # Declare the helm repository of longhorn
  - repository-manifest.yaml
  # Declare the helm chart of longhorn
  - chart-manifest.yaml
  # Declare the helm release of longhorn
  - release-manifest.yaml
