apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 1h
  releaseName: longhorn-controller
  targetNamespace: longhorn-system
  chartRef:
    kind: HelmChart
    name: longhorn
    namespace: longhorn-system
