apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Declare the namespace of nott
  - namespace-manifest.yaml
  # Declare the flux provider of nott
  - provider-manifest.yaml
