apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Declare the namespace of prometheus
  - namespace-manifest.yaml
  # Declare the helm repository of prometheus
  - repository-manifest.yaml
  # Declare the helm chart of prometheus
  - chart-manifest.yaml
  # Declare the helm release of prometheus
  - release-manifest.yaml
