apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus
  namespace: prometheus-system
spec:
  interval: 1h
  url: https://prometheus-community.github.io/helm-charts
