apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-issuer
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./configurations/cluster-issuer
  prune: true
  wait: true
  dependsOn:
    - name: cert-manager
  patches:
    - patch: |-
        - op: replace
          path: /spec/acme/email
          value: "support@noynto.me"
      target:
        kind: ClusterIssuer
        name: lets-encrypt
    - patch: |-
        - op: replace
          path: /spec/acme/server
          value: "https://acme-v02.api.letsencrypt.org/directory"
      target:
        kind: ClusterIssuer
        name: lets-encrypt
