apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Declare the namespace of sealed-secrets
  - namespace-manifest.yaml
  # Declare the helm repository of sealed-secrets
  - repository-manifest.yaml
  # Declare the helm chart of sealed-secrets
  - chart-manifest.yaml
  # Declare the helm release of sealed-secrets
  - release-manifest.yaml
