apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: grafana
  namespace: grafana-system
spec:
  interval: 5m
  chart: grafana
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: grafana
  version: 8.8.2
