---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook
  namespace: nott-system
spec:
  encryptedData:
    address: AgCpbJajXNN7KmpLaHPNrBSQ618syXUTUBVINqVMCfBAds/c7Rswi+iYR+WsNLYfMOpJeNp/4ZzN4a8x/pb+wfEt/HcaWYGYnvtbmKbiku9dujLUKfGyhs7z4q4kb+nHRV/FwgqUeodco5ofzc5wbtC6EaKRyKpdXWGk6CuVAEpErNlI50Bjqclym3fAvKO6xEMlbuG/EQTP5AafI4jgcKkzTCEDnCE5IautbMBxp6999VR+IUpcjzKlA8RBZGi1aSao58j3fLmFcgjASE5f4F6FPDjpL8yT8E3wEQLxK4nw6+kZbPg/0cxe3UejhpFJo4zAg0AaxvMbcPE6uNmJXJe8P77Z440LVcJ0CSiDaecT2hi5sdyXGm0JxO8O+6vVWC2SK0I3OHk0ugCrzWQ8rgfr3E9E/9hx/kb/erwg9R6qjnE56/g1eC9WnIcenRdEahB+5rdqmnPtIeNohqmVvI37usDFbASHleZe1bnfEM5JJ/uIGT5rDr7oPOIfuF+6xP+1z2F98gVkvorP4QXLYJsFSR8nREOJwrnVHPXZQwY0LiuOUt+79qiYUspLdYb9u/qGXWBExKTvu302Z5Zab/hBNq18eeBuVETUMsuYfuQnUVfW8v7ITQz5fBLMkz1+ZuUFWoV3ksKCqRuoNz1zSh4hg0UVKCSQCltLiAJmSnuqqLXhjTC/Xaa78Unx6mRVxt8ohCPI6rWL5nFhM0zFp4KJVL/uvJi8Ef/JbGzb+DjXyg6bEO8n8ZG29X6Vr9NqMkD95ERU7TeNsQ4Sm5vI/sXBitI1OwEArGGpCfGQWml417UnumI9be0erxl4bzBHrYeXVK/AXRhFFd99Cfl9+vdd6VFlOUFe1xjV
  template:
    metadata:
      creationTimestamp: null
      name: webhook
      namespace: nott-system
    type: Opaque
